New celery beat for LMS tasks
hypothesis/h-periodic pull request #211
Opened 2022-06-27 14:01 UTC by marcospri

Needs https://github.com/hypothesis/lms/pull/4142 merged first

`LMS_BROKER_URL` already set on prod/qa and Canada environments.

# Testing

- Checkout https://github.com/hypothesis/lms/pull/4142 on LMS and `make services dev`
- Change the perodicity of the task here to something like `minutes=1`, `make dev`
- See the executing of the task on LMS's `make dev` logs.

2022-06-27 14:02 UTC, marcospri commented on tests/unit/h_periodic/lms_beat_test.py
> +# This is for some dodgy test coverage
Copied this from the checkmate equivalent. 

This is probably a little bit better tha ignoring the file if the config file (ie if we add more functions here coverage won't be complete).

2022-06-27 14:02 UTC, marcospri commented on h_periodic/lms_beat.py
> +            "schedule": timedelta(days=1),
Run this once a day.

2022-06-28 10:55 UTC, jon-betts requested changes
The local config works, but I think there's a typo in the live config.

It would also be nice to document the new environment variable `DISABLE_LMS_BEAT`.

2022-06-28 10:55 UTC, jon-betts commented on conf/supervisord.conf
> +[program:checkmate-beat]
```suggestion
[program:lms-beat]
```
?

2022-06-28 10:55 UTC, jon-betts commented on README.markdown
>  | `DISABLE_CHECKMATE_BEAT` | Whether to disable the `checkmate_beat` process | `true` to disable the `checkmate_beat` process, `false` to leave it enabled. Defaults to `false` (leave it enabled) |
A line here about `DISABLE_LMS_BEAT`?

2022-06-28 10:55 UTC, jon-betts commented on .gitignore
> +*-celerybeat.pid
:+1:

2022-06-29 07:55 UTC, merged